// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/activity-logs": {
    params: {};
  };
  "/companies": {
    params: {};
  };
  "/dashboard": {
    params: {};
  };
  "/vendors": {
    params: {};
  };
  "/work-orders": {
    params: {};
  };
  "/work-orders/:id": {
    params: {
      "id": string;
    };
  };
  "/work-orders/:id/edit": {
    params: {
      "id": string;
    };
  };
  "/work-orders/create": {
    params: {};
  };
  "/*": {
    params: {
      "*": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/activity-logs" | "/companies" | "/dashboard" | "/vendors" | "/work-orders" | "/work-orders/:id" | "/work-orders/:id/edit" | "/work-orders/create" | "/*";
  };
  "./page.jsx": {
    id: "page";
    page: "/";
  };
  "./activity-logs/page.jsx": {
    id: "activity-logs/page";
    page: "/activity-logs";
  };
  "./companies/page.jsx": {
    id: "companies/page";
    page: "/companies";
  };
  "./dashboard/page.jsx": {
    id: "dashboard/page";
    page: "/dashboard";
  };
  "./vendors/page.jsx": {
    id: "vendors/page";
    page: "/vendors";
  };
  "./work-orders/page.jsx": {
    id: "work-orders/page";
    page: "/work-orders";
  };
  "./work-orders/[id]/page.jsx": {
    id: "work-orders/[id]/page";
    page: "/work-orders/:id";
  };
  "./work-orders/[id]/edit/page.jsx": {
    id: "work-orders/[id]/edit/page";
    page: "/work-orders/:id/edit";
  };
  "./work-orders/create/page.jsx": {
    id: "work-orders/create/page";
    page: "/work-orders/create";
  };
  "./__create/not-found.tsx": {
    id: "__create/not-found";
    page: "/" | "/*";
  };
};

type RouteModules = {
  "root": typeof import("./src/app/root.tsx");
  "page": typeof import("./src/app/./page.jsx");
  "activity-logs/page": typeof import("./src/app/./activity-logs/page.jsx");
  "companies/page": typeof import("./src/app/./companies/page.jsx");
  "dashboard/page": typeof import("./src/app/./dashboard/page.jsx");
  "vendors/page": typeof import("./src/app/./vendors/page.jsx");
  "work-orders/page": typeof import("./src/app/./work-orders/page.jsx");
  "work-orders/[id]/page": typeof import("./src/app/./work-orders/[id]/page.jsx");
  "work-orders/[id]/edit/page": typeof import("./src/app/./work-orders/[id]/edit/page.jsx");
  "work-orders/create/page": typeof import("./src/app/./work-orders/create/page.jsx");
  "__create/not-found": typeof import("./src/app/./__create/not-found.tsx");
};